UPDATE DDZL_ZLZLS2
SET 
    DDZL_ZLZLS2.CSBH = Source.CSBH,
    DDZL_ZLZLS2.MJBH = Source.MJBH,
    DDZL_ZLZLS2.CLSL = Source.CLSL,
    DDZL_ZLZLS2.USAGE = Source.USAGE,
    DDZL_ZLZLS2.USERID = 'SYSTEM',
    DDZL_ZLZLS2.USERDATE = Source.USERDATE
FROM (
    SELECT 
        A.ZLBH, A.BWBH, A.CLBH, A.SIZE, A.YN,
        A.CSBH, A.MJBH, A.CLSL, A.USAGE, A.USERDATE, A.USERID
    FROM ZLZLS2 A
    INNER JOIN DDZL ON DDZL.DDBH = A.ZLBH
    INNER JOIN DDZL_ZLZLS2 B ON A.ZLBH = B.ZLBH 
        AND A.CLBH = B.CLBH AND A.BWBH = B.BWBH AND A.SIZE = B.SIZE AND A.YN = B.YN
    WHERE A.USERDATE > GetDate() - 3 
      AND A.USERDATE >= '2025-12-20'
      AND (A.CLSL <> B.CLSL OR A.USAGE <> B.USAGE OR A.CSBH <> B.CSBH OR A.MJBH <> B.MJBH)
      AND DDZL.YN IN (1, 2)
      AND A.USERDATE >= B.USERDATE
      AND (B.USERID = 'SYSTEM' OR A.USERID = B.USERID)
) AS Source
WHERE Source.ZLBH = DDZL_ZLZLS2.ZLBH 
  AND Source.CLBH = DDZL_ZLZLS2.CLBH
  AND Source.BWBH = DDZL_ZLZLS2.BWBH 
  AND Source.SIZE = DDZL_ZLZLS2.SIZE 
  AND Source.YN = DDZL_ZLZLS2.YN



  DELETE FROM DDZL_ZLZLS2
FROM (
    SELECT 
        D.ZLBH, D.CLBH, D.BWBH, D.SIZE, D.YN 
    FROM DDZL_ZLZLS2 D
    LEFT JOIN DDZL ON DDZL.DDBH = D.ZLBH
    LEFT JOIN ZLZLS2 S ON S.ZLBH = D.ZLBH 
        AND S.CLBH = D.CLBH AND S.BWBH = D.BWBH 
        AND S.SIZE = D.SIZE AND S.YN = D.YN
    WHERE S.BWBH IS NULL  
      AND D.USERID = 'SYSTEM'
      AND DDZL.YN IN (1, 2) 
      AND DDZL.ShipDate > GetDate()
) AS ZL 
WHERE ZL.ZLBH = DDZL_ZLZLS2.ZLBH 
  AND ZL.CLBH = DDZL_ZLZLS2.CLBH
  AND ZL.BWBH = DDZL_ZLZLS2.BWBH 
  AND ZL.SIZE = DDZL_ZLZLS2.SIZE 
  AND ZL.YN = DDZL_ZLZLS2.YN



  INSERT INTO DDZL_ZLZLS2 (ZLBH, XH, BWBH, CSBH, MJBH, CLBH, ZMLB, SIZE, CLSL, USAGE, USERID, USERDATE, YN)
SELECT 
    S.ZLBH, S.XH, S.BWBH, S.CSBH, S.MJBH, S.CLBH, S.ZMLB, 
    S.SIZE, S.CLSL, S.USAGE, 'SYSTEM', S.USERDATE, S.YN
FROM ZLZLS2 S
LEFT JOIN DDZL ON DDZL.DDBH = S.ZLBH
LEFT JOIN DDZL_ZLZLS2 D ON S.ZLBH = D.ZLBH 
    AND S.CLBH = D.CLBH AND S.BWBH = D.BWBH AND S.SIZE = D.SIZE AND S.YN = D.YN
WHERE S.ZLBH LIKE '[JHT]%'
  AND S.USERDATE >= DATEADD(DAY, -2, GETDATE())
  AND DDZL.YN IN (1, 2)  
  AND D.BWBH IS NULL 
  AND (S.YN = 1 OR S.YN = 2)
  AND NOT EXISTS (
      SELECT 1 FROM DDZL_ZLZLS2 AS checkUser 
      WHERE checkUser.ZLBH = S.ZLBH AND checkUser.USERID <> 'SYSTEM'
  )