program Account;

uses
  Forms,
  windows,
  main1 in 'source\main1.pas' {main},
  ulogin in 'source\ulogin.pas' {LOGIN},
  DM3 in 'source\DM3.pas' {DM2: TDataModule},
  FirstStock1 in 'Source\FirstStock1.pas' {FirstStock},
  ExtraCon1 in 'Source\ExtraCon1.pas' {ExtraCon},
  EntryConfirm1 in 'Source\EntryConfirm1.pas' {EntryConfirm},
  EntryPur1 in 'Source\SN11\EntryPur1.pas' {EntryPur},
  DeliverList1 in 'Source\DeliverList1.pas' {DeliverList},
  DeliverCon1 in 'Source\DeliverCon1.pas' {DeliverCon},
  AccountCal1 in 'Source\AccountCal1.pas' {AccountCal},
  StockList1 in 'Source\StockList1.pas' {StockList},
  StockList_Print1 in 'Source\StockList_Print1.pas' {StockList_Print},
  AccountCal_entry1 in 'Source\AccountCal_entry1.pas' {AccountCal_entry},
  AdjustDeliver1 in 'Source\AdjustDeliver1.pas' {AdjustDeliver},
  AdjustEntry1 in 'Source\AdjustEntry1.pas' {AdjustEntry},
  AdjustExtra1 in 'Source\AdjustExtra1.pas' {AdjustExtra},
  AccountStock_print1 in 'Source\AccountStock_print1.pas' {AccountStock_print},
  FirstStock_Print1 in 'Source\FirstStock_Print1.pas' {FirstStock_Print},
  Entry_Print1 in 'Source\SN11\Entry_Print1.pas' {Entry_Print},
  EntryCheck1 in 'Source\EntryCheck1.pas' {EntryCheck},
  EntryCheck_Print1 in 'Source\EntryCheck_Print1.pas' {EntryCheck_Print},
  ExtraInCheck1 in 'Source\ExtraInCheck1.pas' {ExtraInCheck},
  ExtraInCheck_Print1 in 'Source\ExtraInCheck_Print1.pas' {ExtraInCheck_Print},
  DeliverCheck1 in 'Source\SN1741\DeliverCheck1.pas' {DeliverCheck},
  DeliverCheck_Print1 in 'Source\DeliverCheck_Print1.pas' {DeliverCheck_Print},
  ExtraOutCheck1 in 'Source\ExtraOutCheck1.pas' {ExtraOutCheck},
  ExtraOutCheck_Print1 in 'Source\ExtraOutCheck_Print1.pas' {ExtraOutCheck_Print},
  MaterialMonth1 in 'Source\SN176\MaterialMonth1.pas' {MaterialMonth},
  MaterialMonth_Print1 in 'Source\MaterialMonth_Print1.pas' {MaterialMonth_Print},
  OrderreplenishCost1 in 'Source\OrderreplenishCost1.pas' {OrderreplenishCost},
  MaterialNoQty1 in 'Source\MaterialNoQty1.pas' {MaterialNoQty},
  MaterialNoQty_Print1 in 'Source\MaterialNoQty_Print1.pas' {MaterialNoQty_Print},
  PayableMaterial1 in 'Source\PayableMaterial1.pas' {PayableMaterial},
  Payabledetail1 in 'Source\Payabledetail1.pas' {Payabledetail},
  EmbroiderPay1 in 'Source\EmbroiderPay1.pas' {EmbroiderPay},
  PayableMaterial_Print1 in 'Source\PayableMaterial_Print1.pas' {PayableMaterial_Print},
  PayableDetail_Print1 in 'Source\PayableDetail_Print1.pas' {PayableDetail_Print},
  PayableLit1 in 'Source\PayableLit1.pas' {PayableLit},
  AccountBank1 in 'Source\AccountBank1.pas' {AccountBank},
  DebitNote1 in 'Source\DebitNote1.pas' {DebitNote},
  Payabled_CL1 in 'Source\Payabled_CL1.pas' {Payabled_CL},
  Payable_ZS1 in 'Source\Payable_ZS1.pas' {Payable_ZS},
  Payable_ZH1 in 'Source\SN27\Payable_ZH1.pas' {Payable_ZH},
  CostMaterial1 in 'Source\CostMaterial1.pas' {CostMaterial},
  CostMaterial_Print1 in 'Source\CostMaterial_Print1.pas' {CostMaterial_Print},
  CostMaterialDet1 in 'Source\CostMaterialDet1.pas' {CostMaterialDet},
  CostMaterialDet_Print1 in 'Source\CostMaterialDet_Print1.pas' {CostMaterialDet_Print},
  CostPrice1 in 'Source\CostPrice1.pas' {CostPrice},
  CostPrice_ZH1 in 'Source\CostPrice_ZH1.pas' {CostPrice_ZH},
  CostPrice_DD1 in 'Source\CostPrice_DD1.pas' {CostPrice_DD},
  CostFee1 in 'Source\CostFee1.pas' {CostFee},
  CostFee_Det1 in 'Source\CostFee_Det1.pas' {CostFee_Det},
  CostFeeDep1 in 'Source\CostFeeDep1.pas' {CostFeeDep},
  CostFeeDep_Det1 in 'Source\CostFeeDep_Det1.pas' {CostFeeDep_Det},
  OrderKeyList1 in 'Source\OrderKeyList1.pas' {OrderKeyList},
  ReplenishFee1 in 'Source\ReplenishFee1.pas' {ReplenishFee},
  ReplenishFee_Det1 in 'Source\ReplenishFee_Det1.pas' {ReplenishFee_Det},
  ReplenishFeeDep1 in 'Source\ReplenishFeeDep1.pas' {ReplenishFeeDep},
  ReplenishFeeDep_Det1 in 'Source\ReplenishFeeDep_Det1.pas' {ReplenishFeeDep_Det},
  AccountDel1 in 'Source\AccountDel1.pas' {AccountDel},
  AccountEntry1 in 'Source\AccountEntry1.pas' {AccountEntry},
  AccountDelReason1 in 'Source\AccountDelReason1.pas' {AccountDelReason},
  AccountDelDep1 in 'Source\AccountDelDep1.pas' {AccountDelDep},
  AccountDelDet1 in 'Source\AccountDelDet1.pas' {AccountDelDet},
  AccountDelRea_Det1 in 'Source\AccountDelRea_Det1.pas' {AccountDelRea_Det},
  AccountDelDep_Det1 in 'Source\AccountDelDep_Det1.pas' {AccountDelDep_Det},
  AccountEntry_Det1 in 'Source\AccountEntry_Det1.pas' {AccountEntry_Det},
  AccountEntryDep1 in 'Source\AccountEntryDep1.pas' {AccountEntryDep},
  AccountEntryDep_Det1 in 'Source\AccountEntryDep_Det1.pas' {AccountEntryDep_Det},
  AccountFix1 in 'Source\AccountFix1.pas' {AccountFix},
  MaterialEntryList1 in 'Source\MaterialEntryList1.pas' {MaterialEntryList},
  CostOrderList1 in 'Source\CostOrderList1.pas' {CostOrderList},
  CostOrderList_DD1 in 'Source\CostOrderList_DD1.pas' {CostOrderList_DD},
  CostOrderList_Det1 in 'Source\CostOrderList_Det1.pas' {CostOrderList_Det},
  FeeNo1 in 'Source\FeeNo1.pas' {FeeNo},
  FeeMonth1 in 'Source\FeeMonth1.pas' {FeeMonth},
  DailyExchange1 in 'Source\DailyExchange1.pas' {DailyExchange},
  PayMentCon1 in 'Source\SN27\PayMentCon1.pas' {PayMentCon},
  Payable_print1 in 'Source\Payable_print1.pas' {Payable_print},
  PayMentCon_Price1 in 'Source\SN27\PayMentCon_Price1.pas' {PayMentCon_Price},
  Payable_Det1 in 'Source\Payable_Det1.pas' {Payable_Det},
  EntryPur_Price1 in 'Source\SN11\EntryPur_Price1.pas' {EntryPur_Price},
  Entry_PrintTW1 in 'Source\Entry_PrintTW1.pas' {Entry_PrintTW},
  FirstStock_Price1 in 'Source\FirstStock_Price1.pas' {FirstStock_Price},
  FirstStock_PriceM1 in 'Source\FirstStock_PriceM1.pas' {FirstStock_PriceM},
  AdjustDeliver_CL1 in 'Source\AdjustDeliver_CL1.pas' {AdjustDeliver_CL},
  DeliverCheck_Price1 in 'Source\DeliverCheck_Price1.pas' {DeliverCheck_Price},
  DeliverCheck_Son1 in 'Source\DeliverCheck_Son1.pas' {DeliverCheck_Son},
  Payable_print21 in 'Source\Payable_print21.pas' {Payable_print2},
  PayableLit_Check1 in 'Source\PayableLit_Check1.pas' {PayableLit_Check},
  AdjustDelPrice1 in 'Source\AdjustDelPrice1.pas' {AdjustDelPrice},
  AdjustEntryACC1 in 'Source\AdjustEntryACC1.pas' {AdjustEntryACC},
  FeeMaterialOrd1 in 'Source\FeeMaterialOrd1.pas' {FeeMaterialOrd},
  FeeMaterialOth1 in 'Source\FeeMaterialOth1.pas' {FeeMaterialOth},
  FeeMaterialOrd_Det1 in 'Source\FeeMaterialOrd_Det1.pas' {FeeMaterialOrd_Det},
  CostOrderList_Scan1 in 'Source\CostOrderList_Scan1.pas' {CostOrderList_Scan},
  CostmaterialIn1 in 'Source\CostmaterialIn1.pas' {CostmaterialIn},
  CostOrderList_R31 in 'Source\CostOrderList_R31.pas' {CostOrderList_R3},
  CostOrderList_R21 in 'Source\CostOrderList_R21.pas' {CostOrderList_R2},
  CostOrderList_GC1 in 'Source\CostOrderList_GC1.pas' {CostOrderList_GC},
  CostMaterial_DD1 in 'Source\CostMaterial_DD1.pas' {CostMaterial_DD},
  CostmaterialNo1 in 'Source\CostmaterialNo1.pas' {CostmaterialNo},
  MatType1 in 'Source\MatType1.pas' {MatType},
  MatType_Det1 in 'Source\MatType_Det1.pas' {MatType_Det},
  CostMaterialNoDet1 in 'Source\CostMaterialNoDet1.pas' {CostMaterialNoDet},
  CostmaterialAcc1 in 'Source\CostmaterialAcc1.pas' {CostmaterialAcc},
  CostMaterialAccDet1 in 'Source\CostMaterialAccDet1.pas' {CostMaterialAccDet},
  Adjustingp in 'Source\Adjustingp.pas' {Adjusting},
  AdjustingprintP in 'Source\AdjustingprintP.pas' {Adjustingprint},
  Payabl_CMSMQ1 in 'Source\SN27\Payabl_CMSMQ1.pas' {Payable_CMSMQ},
  scandata1 in 'source\SN178\scandata1.pas' {ScanData},
  scandata_Print1 in 'source\SN178\scandata_Print1.pas' {scandata_Print},
  Payable_ACTMA1 in 'Source\SN27\Payable_ACTMA1.pas' {Payable_ACTMA},
  scandataout1 in 'Source\SN178\scandataout1.pas' {scandataout},
  EntryCheckPay1 in 'Source\SN232\EntryCheckPay1.pas' {EntryCheckPay},
  DeliverCheckOrder1 in 'Source\SN1742\DeliverCheckOrder1.pas' {DeliverCheckOrder},
  Exchange1 in 'Source\SN11\Exchange1.pas' {Exchange},
  KiemtraKCRKCX1 in 'Source\SN189\KiemtraKCRKCX1.pas' {KiemtraKCRKCX},
  Semifinished1 in 'Source\SN1743\Semifinished1.pas' {Semifinished},
  Semifinished_Det1 in 'Source\SN1743\Semifinished_Det1.pas' {Semifinished_Det},
  AccMonthStock1 in 'Source\SN611\AccMonthStock1.pas' {AccMonthStock},
  Consumer1 in 'Source\SN81\Consumer1.pas' {Consumer},
  frmCWHL_Invoice1 in 'Source\SN81\frmCWHL_Invoice1.pas' {frmCWHL_Invoice},
  Report_NXT1 in 'Source\SN62\Report_NXT1.pas' {Report_NXT},
  Report_SCT1 in 'Source\SN63\Report_SCT1.pas' {Report_SCT},
  Report_NXT_Print1 in 'Source\SN62\Report_NXT_Print1.pas' {NXT_Print_S},
  Report_SCT_Print1 in 'Source\SN63\Report_SCT_Print1.pas' {Report_SCT_Print},
  StockShoeMonth1 in 'Source\SN1793\StockShoeMonth1.pas' {StockShoeMonth},
  StockShoeMonth_Print1 in 'Source\SN1793\StockShoeMonth_Print1.pas' {StockShoeMonth_Print},
  SemiMaterialMonth1 in 'Source\SN17921\SemiMaterialMonth1.pas' {SemiMaterialMonth},
  SemiMaterialMonth_ZZ1 in 'Source\SN17921\SemiMaterialMonth_ZZ1.pas' {SemiMaterialMonth_ZZ},
  SampleFinishShoeStock_Print1 in 'Source\SN1793\SampleFinishShoeStock_Print1.pas' {SampleFinishShoeStock_Print},
  CBYFinishShoeStock_Print1 in 'Source\SN1793\CBYFinishShoeStock_Print1.pas' {CBYFinishShoeStock_Print},
  SampleShoeStock_Detail1 in 'Source\SN1793\SampleShoeStock_Detail1.pas' {SampleShoeStock_Detail},
  CBYShoeStock_Detail1 in 'Source\SN1793\CBYShoeStock_Detail1.pas' {CBYShoeStock_Detail},
  SetupSCBHGT1 in 'Source\SN1791\SetupSCBHGT1.pas' {SetupSCBHGT},
  MaterialCostReport_Print1 in 'Source\SN17921\MaterialCostReport_Print1.pas' {MaterialCostReport_Print},
  PaymentVATNO_DEP1 in 'Source\SN233\PaymentVATNO_DEP1.pas' {PaymentVATNO_DEP},
  PaymentVATNO_HD1 in 'Source\SN233\PaymentVATNO_HD1.pas' {PaymentVATNO_HD},
  PaymentVATNO_Print1 in 'Source\SN233\PaymentVATNO_Print1.pas' {PaymentVATNO_Print},
  PaymentVATNO_TK1 in 'Source\SN233\PaymentVATNO_TK1.pas' {PaymentVATNO_TK},
  PaymentVATNO_ZS1 in 'Source\SN233\PaymentVATNO_ZS1.pas' {PaymentVATNO_ZS},
  PaymentVATNO1 in 'Source\SN233\PaymentVATNO1.pas' {PaymentVATNO},
  CBY_ExtraCon1 in 'Source\SN1B\CBY_ExtraCon1.pas' {CBY_ExtraCon},
  Payabled_CL_JGCBY1 in 'Source\Payabled_CL_JGCBY1.pas' {Payabled_CL_JGCBY},
  AdjustCBYExtraCon1 in 'Source\SN18B\AdjustCBYExtraCon1.pas' {Adjust_CBY_Extra_Con},
  ExtraInCheckCBY_Print1 in 'Source\ExtraInCheckCBY_Print1.pas' {ExtraInCheckCBY_Print},
  Adjust_CPNVL_PB1 in 'Source\SN17921\Adjust_CPNVL_PB1.pas' {Adjust_CPNVL_PB},
  CBY_SemiMaterialMonth1 in 'Source\SN179221\CBY_SemiMaterialMonth1.pas' {CBY_SemiMaterialMonth},
  CBY_MaterialCostReport_Print1 in 'Source\SN179221\CBY_MaterialCostReport_Print1.pas' {CBY_MaterialCostReport_Print},
  CBY_SemiMaterialMonth_ZZ1 in 'Source\SN179221\CBY_SemiMaterialMonth_ZZ1.pas' {CBY_SemiMaterialMonth_ZZ},
  Deliver_Print1 in 'Source\SN18C\Deliver_Print1.pas' {Deliver_Print},
  Deliver_Account1 in 'Source\SN18C\Deliver_Account1.pas' {Deliver_Account},
  Adjust_CPNVL_PB_Chemical1 in 'Source\SN17923\Adjust_CPNVL_PB_Chemical1.pas' {Adjust_CPNVL_PB_Chemical},
  ChemicalCostReport_Print1 in 'Source\SN17923\ChemicalCostReport_Print1.pas' {ChemicalCostReport_Print},
  SemiChemicalMonth_ZZ1 in 'Source\SN17923\SemiChemicalMonth_ZZ1.pas' {SemiChemicalMonth_ZZ},
  SemiChemicalMonth1 in 'Source\SN17923\SemiChemicalMonth1.pas' {SemiChemicalMonth},
  OutsoleStockMonth_Print1 in 'Source\SN1793\OutsoleStockMonth_Print1.pas' {OutsoleStockMonth_Print},
  Adjust_CPNVL_PB_CDC1 in 'Source\SN179221\Adjust_CPNVL_PB_CDC1.pas' {Adjust_CPNVL_PB_CDC},
  DelOther_PrintA51 in 'Source\SN18C\DelOther_PrintA51.pas' {DelOther_PrintA5},
  DelMaterial_PrintA51 in 'Source\SN18C\DelMaterial_PrintA51.pas' {DelMaterial_PrintA5},
  Delother_C_PrintA51 in 'Source\SN18C\DelOther_C_PrintA51.pas' {Delother_C_PrintA5},
  DelOther_M_PrintA51 in 'Source\SN18C\DelOther_M_PrintA51.pas' {DelOther_M_PrintA5},
  SemiMaterialMonth_Detail1 in 'Source\SN17921\SemiMaterialMonth_Detail1.pas' {SemiMaterialMonth_Detail},
  CBY_SemiMaterialMonth_Detail1 in 'Source\SN179221\CBY_SemiMaterialMonth_Detail1.pas' {CBY_SemiMaterialMonth_Detail},
  SemiChemicalMonth_Detail1 in 'Source\SN17923\SemiChemicalMonth_Detail1.pas' {SemiChemicalMonth_Detail},
  Entry_Account1 in 'Source\SN18D\Entry_Account1.pas' {Entry_Account},
  Entry_RePrintSumA51 in 'Source\SN18D\Entry_RePrintSumA51.pas' {Entry_RePrintSumA5},
  PaymentVATNO_PrintHD1 in 'Source\SN233\PaymentVATNO_PrintHD1.pas' {PaymentVATNO_PrintHD},
  PaymentVATNO_PrintTT1 in 'Source\SN233\PaymentVATNO_PrintTT1.pas' {PaymentVATNO_PrintTT},
  PaymentVATNO_PrintTTHD1 in 'Source\SN233\PaymentVATNO_PrintTTHD1.pas' {PaymentVATNO_PrintTTHD},
  PaymentUng1 in 'Source\SN233\PaymentUng1.pas' {PaymentUng},
  PyamentUngHD1 in 'Source\SN233\PyamentUngHD1.pas' {PaymentUngHD},
  PaymentConfirmCancel3311 in 'Source\SN2341\PaymentConfirmCancel3311.pas' {PaymentConfirmCancel331},
  PaymentConfirmCancel1121 in 'Source\SN2342\PaymentConfirmCancel1121.pas' {PaymentConfirmCancel112},
  VATNODataTracking1 in 'Source\SN2343\VATNODataTracking1.pas' {VATNODataTracking},
  PaymentVATNO_Print_TB1 in 'Source\SN233\PaymentVATNO_Print_TB1.pas' {PaymentVATNO_Print_TB},
  PaymentVATNO_PrintHD_TB1 in 'Source\SN233\PaymentVATNO_PrintHD_TB1.pas' {PaymentVATNO_PrintHD_TB},
  PaymentVATNO_PrintTT_TB1 in 'Source\SN233\PaymentVATNO_PrintTT_TB1.pas' {PaymentVATNO_PrintTT_TB},
  PaymentVATNO_PrintTTHD_TB1 in 'Source\SN233\PaymentVATNO_PrintTTHD_TB1.pas' {PaymentVATNO_PrintTTHD_TB},
  EntryCheck_CCDC1 in 'Source\SN17A\EntryCheck_CCDC1.pas' {EntryCheck_CCDC},
  SemiMaterialMonth_Sample1 in 'Source\SN179222\SemiMaterialMonth_Sample1.pas' {SemiMaterialMonth_Sample},
  Adjust_CPNVL_PB_Sample1 in 'Source\SN179222\Adjust_CPNVL_PB_Sample1.pas' {Adjust_CPNVL_PB_Sample},
  SemiMaterialMonth_Sample_Detail1 in 'Source\SN179222\SemiMaterialMonth_Sample_Detail1.pas' {SemiMaterialMonth_Sample_Detail},
  SemiMaterialMonth_Sample_Print1 in 'Source\SN179222\SemiMaterialMonth_Sample_Print1.pas' {SemiMaterialMonth_Sample_Print},
  SemiMaterialMonth_CBY1 in 'Source\SN179223\SemiMaterialMonth_CBY1.pas' {SemiMaterialMonth_CBY},
  Adjust_CPNVL_PB_CBY1 in 'Source\SN179223\Adjust_CPNVL_PB_CBY1.pas' {Adjust_CPNVL_PB_CBY},
  SemiMaterialMonth_CBY_Detail1 in 'Source\SN179223\SemiMaterialMonth_CBY_Detail1.pas' {SemiMaterialMonth_CBY_Detail},
  SemiMaterialMonth_CBY_ZZ1 in 'Source\SN179223\SemiMaterialMonth_CBY_ZZ1.pas' {SemiMaterialMonth_CBY_ZZ},
  SemiMaterialMonth_CBY_Print1 in 'Source\SN179223\SemiMaterialMonth_CBY_Print1.pas' {SemiMaterialMonth_CBY_Print},
  Import_VATNo1 in 'Source\SN81\Import_VATNo1.pas' {Import_VATNo},
  Supplier_KPI1 in 'Source\SN64\Supplier_KPI1.pas' {Supplier_KPI},
  SemiMaterialMonth_Skechers1 in 'Source\SN179224\SemiMaterialMonth_Skechers1.pas' {SemiMaterialMonth_Skechers},
  SemiMaterialMonth_Skechers_Print1 in 'Source\SN179224\SemiMaterialMonth_Skechers_Print1.pas' {SemiMaterialMonth_Skechers_Print},
  PaymentVATNO_Print_TB_VN1 in 'Source\SN233\PaymentVATNO_Print_TB_VN1.pas' {PaymentVATNO_Print_TB_VN},
  PaymentVATNO_PrintPTU1 in 'Source\SN233\PaymentVATNO_PrintPTU1.pas' {PaymentVATNO_PrintPTU},
  PaymentVATNO_PrintTTTU1 in 'Source\SN233\PaymentVATNO_PrintTTTU1.pas' {PaymentVATNO_PrintTTTU},
  PaymentVATNO_PTU1 in 'Source\SN233\PaymentVATNO_PTU1.pas' {PaymentVATNO_PTU},
  PaymentVATNO_PrintPTU_USD1 in 'Source\SN233\PaymentVATNO_PrintPTU_USD1.pas' {PaymentVATNO_PrintPTU_USD},
  PaymentVATNO_PrintTTTU_USD1 in 'Source\SN233\PaymentVATNO_PrintTTTU_USD1.pas' {PaymentVATNO_PrintTTTU_USD},
  SemiMaterialMonth_Sample_ZZ1 in 'Source\SN179222\SemiMaterialMonth_Sample_ZZ1.pas' {SemiMaterialMonth_Sample_ZZ},
  CBY_DeliverCon1 in 'Source\SN1C\CBY_DeliverCon1.pas' {CBY_DeliverCon},
  CBY_AdjustDeliver1 in 'Source\SN18E\CBY_AdjustDeliver1.pas' {CBY_AdjustDeliver},
  VATNOData1 in 'Source\SN1A1\VATNOData1.pas' {VATNOData},
  COSTData1 in 'Source\SN1A2\COSTData1.pas' {COSTData},
  SemiMonthTotal1 in 'Source\SN179242\SemiMonthTotal1.pas' {SemiMonthTotal},
  ImportRYPrice1 in 'Source\SN179241\ImportRYPrice1.pas' {ImportRYPrice},
  SemiImportPrice1 in 'Source\SN179241\SemiImportPrice1.pas' {SemiImportPrice},
  Adjust_CP1 in 'Source\SN179242\Adjust_CP1.pas' {Adjust_CP},
  MonthSemiFinishProduct1 in 'Source\SN179243\MonthSemiFinishProduct1.pas' {MonthSemiFinishProduct},
  PaymentVATNO_PrintPTU_TB1 in 'Source\SN233\PaymentVATNO_PrintPTU_TB1.pas' {PaymentVATNO_PrintPTU_TB},
  PaymentVATNO_PrintTTTU_TB1 in 'Source\SN233\PaymentVATNO_PrintTTTU_TB1.pas' {PaymentVATNO_PrintTTTU_TB};

{$R *.res}

var   MutexHandle:Thandle;
begin
  Mutexhandle:=windows.CreateMutex(nil,true,'Account.exe');
  if   Mutexhandle<>0   then
    begin
      if   getlasterror=windows.ERROR_ALREADY_EXISTS   then
        begin
          closehandle(Mutexhandle);
          halt;
        end;
    end;

 Application.Initialize;
  login:=tlogin.create(application);
  login.Show;
  login.Update;
//  Application.CreateForm(TLOGIN, LOGIN);
  Application.Title := 'Lai Yih ERP System--Account';
  Application.CreateForm(TDM2, DM2);
  Application.CreateForm(Tmain, main);
  login.hide;
  login.free;
 Application.Run;

end.
