program Develop;

uses
  Forms,
  windows,
  main1 in 'source\main1.pas' {main},
  ulogin in 'source\ulogin.pas' {LOGIN},
  DM3 in 'source\DM3.pas' {DM2: TDataModule},
  tempmaterialp in 'source\tempmaterialp.pas' {TempMaterial},
  queryformp in 'source\queryformp.pas' {queryform},
  MaterialChengp in 'source\MaterialChengp.pas' {MaterialCheng},
  smapleorderlistp in 'source\smapleorderlistp.pas' {SmapleOrderList},
  SuppNew1 in 'source\SuppNew1.pas' {SuppNew},
  SonMaterial1 in 'source\SonMaterial1.pas' {SonMaterial},
  Quotation1 in 'source\Quotation1.pas' {Quotation},
  Quotation_CL1 in 'source\Quotation_CL1.pas' {Quotation_CL},
  Quotation_Print1 in 'source\Quotation_Print1.pas' {Quotation_Print},
  Quotation_ZS1 in 'source\Quotation_ZS1.pas' {Quotation_ZS},
  PartClass1 in 'source\PartClass1.pas' {PartClass},
  simpleselectp in 'source\simpleselectp.pas' {simpleselect},
  PurOther_BJ1 in 'source\PurOther_BJ1.pas' {PurOther_BJ},
  PurOther_CL1 in 'source\PurOther_CL1.pas' {PurOther_CL},
  PurOther_Print1 in 'source\PurOther_Print1.pas' {PurOther_Print},
  PurOther_safe1 in 'source\PurOther_safe1.pas' {PurOther_safe},
  PurOther_ZS1 in 'source\PurOther_ZS1.pas' {PurOther_ZS},
  PurOther1 in 'source\PurOther1.pas' {PurOther},
  DelOther1 in 'source\DelOther1.pas' {DelOther},
  DelOther_YY1 in 'source\DelOther_YY1.pas' {DelOther_YY},
  DelOther_SCBH1 in 'source\DelOther_SCBH1.pas' {DelOther_SCBH},
  DelOther_Print1 in 'source\DelOther_Print1.pas' {DelOther_Print},
  DelOther_Mat1 in 'source\DelOther_Mat1.pas' {DelOther_Mat},
  DelOther_Dep1 in 'source\DelOther_Dep1.pas' {DelOther_Dep},
  DelOther_CL1 in 'source\DelOther_CL1.pas' {DelOther_CL},
  DelOther_C1 in 'source\DelOther_C1.pas' {DelOther_C},
  DelOther_BL1 in 'source\DelOther_BL1.pas' {DelOther_BL},
  DelOther_C_Print1 in 'source\DelOther_C_Print1.pas' {DelOther_C_Print},
  DelOther_C_SCBH1 in 'source\DelOther_C_SCBH1.pas' {DelOther_C_SCBH},
  DelOther_C_Mat1 in 'source\DelOther_C_Mat1.pas' {DelOther_C_Mat},
  DelOther_C_Dep1 in 'source\DelOther_C_Dep1.pas' {DelOther_C_Dep},
  Purchasecheckp in 'source\Purchasecheckp.pas' {Purchasecheck},
  SampleBOMp in 'source\SN24\SampleBOMp.pas' {SampleBOM},
  PFC_SkuMapp in 'source\SN15\PFC_SkuMapp.pas' {PFC_SkuMap},
  SKUQryp in 'source\SN15\SKUQryp.pas' {SKUQry},
  SampleTracking_Dev1 in 'source\SN251\SampleTracking_Dev1.pas' {SampleTracking_Dev},
  SampleTracking_Pat1 in 'source\SN252\SampleTracking_Pat1.pas' {SampleTracking_Pat},
  SampleTracking_Pur1 in 'source\SN253\SampleTracking_Pur1.pas' {SampleTracking_Pur},
  SampleTracking_Pro1 in 'source\SN254\SampleTracking_Pro1.pas' {SampleTracking_Pro},
  SampleTracking_Quo1 in 'source\SN255\SampleTracking_Quo1.pas' {SampleTracking_Quo},
  SampleTrackReason1 in 'source\SN251\SampleTrackReason1.pas' {SampleTrackReason},
  SampleTrackingRms1 in 'source\SN251\SampleTrackingRms1.pas' {SampleTrackingRms},
  SRList1 in 'source\SN251\SRList1.pas' {SRLIst},
  PurchaseMerge_SupplierName1 in 'source\SN21\PurchaseMerge_SupplierName1.pas' {PurchaseMerge_SupplierName},
  SampleOrder1 in 'source\SN22\SampleOrder1.pas' {SampleOrder},
  SampleOrder_Article1 in 'source\SN22\SampleOrder_Article1.pas' {SampleOrder_Article},
  SampleOrder_Stage1 in 'source\SN22\SampleOrder_Stage1.pas' {SampleOrder_Stage},
  SampleOrder_Curency1 in 'source\SN22\SampleOrder_Curency1.pas' {SampleOrder_Curency},
  SampleOrder_Mat1 in 'source\SN22\SampleOrder_Mat1.pas' {SampleOrder_Mat},
  SampleOrder_Part1 in 'source\SN22\SampleOrder_Part1.pas' {SampleOrder_Part},
  SampleOrder_Supplier1 in 'source\SN22\SampleOrder_Supplier1.pas' {SampleOrder_Supplier},
  SampleMaterial1 in 'source\SN23\SampleMaterial1.pas' {SampleMaterial},
  SampleMaterial_Combinated1 in 'source\SN23\SampleMaterial_Combinated1.pas' {SampleMaterial_Combinated},
  SampleMaterial_CombinatedDev1 in 'source\SN22\SampleMaterial_CombinatedDev1.pas' {SampleMaterial_CombinatedDev},
  SampleMaterial_Mat1 in 'source\SN23\SampleMaterial_Mat1.pas' {SampleMaterial_Mat},
  SampleMaterial_Supplier1 in 'source\SN23\SampleMaterial_Supplier1.pas' {SampleMaterial_Supplier},
  SampleMaterial_SupplierDev1 in 'source\SN22\SampleMaterial_SupplierDev1.pas' {SampleMaterial_SupplierDev},
  MaterialArticle1 in 'source\SN23\MaterialArticle1.pas' {MaterialArticle},
  MQ1 in 'source\SN26\MQ1.pas' {MQ},
  FDStatus1 in 'source\SN34\FDStatus1.pas' {FDStatus},
  FDStatus_AL1 in 'source\SN34\FDStatus_AL1.pas' {FDStatus_AL},
  FDStatus_Bom1 in 'source\SN34\FDStatus_Bom1.pas' {FDStatus_Bom},
  FDStatus_ETD1 in 'source\SN34\FDStatus_ETD1.pas' {FDStatus_ETD},
  FDStatus_FD1 in 'source\SN34\FDStatus_FD1.pas' {FDStatus_FD},
  FDStatus_MEMO1 in 'source\SN34\FDStatus_MEMO1.pas' {FDStatus_MEMO},
  FDStatus_PO1 in 'source\SN34\FDStatus_PO1.pas' {FDStatus_PO},
  FDstatus_Stage1 in 'source\SN34\FDstatus_Stage1.pas' {FDstatus_Stage},
  FDStatus_Article1 in 'source\SN34\FDStatus_Article1.pas' {FDStatus_Article},
  FDStatus_Stock1 in 'source\SN34\FDStatus_Stock1.pas' {FDStatus_Stock},
  DFC1 in 'source\SN64\DFC1.pas' {DFC},
  ShoeTracking1 in 'source\SN256\ShoeTracking1.pas' {ShoeTracking},
  SampleDevelopInformation1 in 'source\SN72\SampleDevelopInformation1.pas' {SampleDevelopInformation},
  FDStatusMaterialChange1 in 'source\SN16\FDStatusMaterialChange1.pas' {FDStatusMaterialChange},
  FDStatusMaterialChange_Stage1 in 'source\SN16\FDStatusMaterialChange_Stage1.pas' {FDStatusMaterialChange_Stage},
  FDStatusMaterialChange_FD1 in 'source\SN16\FDStatusMaterialChange_FD1.pas' {FDStatusMaterialChange_FD},
  FDUnfinished1 in 'source\SN16\FDUnfinished1.pas' {FDUnfinished},
  Showshoepic1 in 'source\SN72\Showshoepic1.pas' {Showshoepic},
  TransferSRStage1 in 'source\SN22\TransferSRStage1.pas' {TransferSRStage},
  MaterialTestFD_FD1 in 'source\SN171\MaterialTestFD_FD1.pas' {MaterialTestFD_FD},
  MaterialTestFD1 in 'source\SN171\MaterialTestFD1.pas' {MaterialTestFD},
  MatlTestFD_Supplier1 in 'source\SN171\MatlTestFD_Supplier1.pas' {MatlTestFD_Supplier},
  FGTTest1 in 'source\SN181\FGTTest1.pas' {FGTTest},
  Calendar1 in 'source\SN181\Calendar1.pas' {Calendar},
  AdiColor1 in 'source\SN181\AdiColor1.pas' {AdiColor},
  MaterialTestFD_TestData1 in 'source\SN171\MaterialTestFD_TestData1.pas' {MaterialTestFD_TestData},
  UseCLZL_LS1 in 'source\SN23\UseCLZL_LS1.pas' {UseCLZL_LS},
  SampleException1 in 'source\SN22\SampleException1.pas' {SampleException},
  FDExcelData1 in 'source\SN741\FDExcelData1.pas' {FDExcelData},
  ArticleChoose1 in 'source\SN75\ArticleChoose1.pas' {ArticleChoose},
  Dep_Choose1 in 'source\SN75\Dep_Choose1.pas' {Dep_Choose},
  KF_FD1 in 'source\SN75\KF_FD1.pas' {KF_FD},
  PaperRoom_Print1 in 'source\SN75\PaperRoom_Print1.pas' {PapaerRoom_print},
  PaperRoom_shoeTest in 'source\SN75\PaperRoom_shoeTest.pas' {PaperRoom},
  PaperSize_Print1 in 'source\SN75\PaperSize_Print1.pas' {PaperSize_Print},
  ShoeTestMat1 in 'source\SN75\ShoeTestMat1.pas' {ShoeTestMat},
  C_Excel in 'source\c_Excel.pas',
  MsgMANAGER in 'source\MsgMANAGER.PAS',
  UWAITFM in 'source\UWAITFM.PAS' {fm_Waitform},
  FDStatusLeadTime_FD1 in 'source\SN35\FDStatusLeadTime_FD1.pas' {FDStatusLeadTime_FD},
  FDstatusLeadTime_Stage1 in 'source\SN35\FDstatusLeadTime_Stage1.pas' {FDstatusLeadTime_Stage},
  FDStatusLeadTime1 in 'source\SN35\FDStatusLeadTime1.pas' {FDStatusLeadTime},
  SamplePlan1 in 'source\SN27\SamplePlan1.pas' {SamplePlan},
  Extra1 in 'source\SN72\Extra1.pas' {Extra},
  BomDataSearch1 in 'source\SN76\BomDataSearch1.pas' {BomDataSearch},
  DeveloperName1 in 'source\SN77\DeveloperName1.pas' {DeveloperName},
  DevCalendar1 in 'source\SN78\DevCalendar1.pas' {DevCalenDar},
  SampleWarehouse1 in 'source\SN28\SampleWarehouse1.pas' {SampleWarehouse},
  DetailChoose1 in 'source\SN75\DetailChoose1.pas' {DetailChoose},
  choosedetail1 in 'source\SN75\choosedetail1.pas' {ChooseDetail},
  SampleCopyChoice1 in 'source\SN22\SampleCopyChoice1.pas' {SampleCopyChoice},
  AnyStock1 in 'source\SN44\AnyStock1.pas' {AnyStock},
  Flexcode1 in 'source\SN29\Flexcode1.pas' {FlexCode},
  SampleOderUserChange1 in 'source\SN79\SampleOderUserChange1.pas' {SampleOderUserChange},
  OrganizationSetting1 in 'source\SN81\OrganizationSetting1.pas' {Organization1},
  QC_ShoeTest1 in 'source\SN91\QC_ShoeTest1.pas' {QC_ShoeTest},
  QC_ShoeTestTB1 in 'source\SN91\QC_ShoeTestTB1.pas' {QC_ShoeTestTB},
  ShoeTestReport1 in 'source\SN92\ShoeTestReport1.pas' {ShoeTestReport},
  MaterialTracking in 'source\SN65\MaterialTracking.pas' {MaterialTracking1},
  SampleDataUpload1 in 'source\SN7A\SampleDataUpload1.pas' {SampleDataUpload},
  Overtime_Report1 in 'source\SN66\Overtime_Report1.pas' {Overtime_Report},
  PC_Memo1 in 'source\SN83\PC_Memo1.pas' {PC_Memo},
  DeveloperLoading1 in 'source\SN67\DeveloperLoading1.pas' {DeveloperLoading},
  SampleAnalysis1 in 'source\SN68\SampleAnalysis1.pas' {SampleAnalysis},
  Barcode93Unit1 in 'source\SN75\Barcode93Unit1.pas',
  ScanTBreceive in 'source\SNA11\ScanTBreceive.pas' {ScanTBReceive1},
  ScanTBComplete in 'source\SNA61\ScanTBComplete.pas' {ScanTBComplete1},
  TBCSTime in 'source\SNA31\TBCSTime.pas' {TBCSTime1},
  MaterialReadyTime in 'source\SNA21\MaterialReadyTime.pas' {MaterialReadyTime1},
  UseStockReport1 in 'source\SN69\UseStockReport1.pas' {UseStockReport},
  NewMaterialList1 in 'source\SN6A\NewMaterialList1.pas' {NewMaterialList},
  LastData1 in 'source\SN7B\LastData1.pas' {LastData},
  LastData_Mat1 in 'source\SN7B\LastData_Mat1.pas' {LastData_Mat},
  LastData_Supplier1 in 'source\SN7B\LastData_Supplier1.pas' {LastData_Supplier},
  MaterialList1 in 'source\SN19\MaterialList1.pas' {MaterialList},
  NewMaterial1 in 'source\SN19\NewMaterial1.pas' {NewMaterial},
  NewMaterialOfSeason1 in 'source\SN19\NewMaterialOfSeason1.pas' {NewMaterialOfSeason},
  RubberPO1 in 'source\SN6B\RubberPO1.pas' {RubberPO},
  RelativeShoes1 in 'source\SN19\RelativeShoes1.pas' {RelativeShoes},
  BasicInformation1 in 'source\SNB1\BasicInformation1.pas' {BasicInformation},
  MoldData_Mat1 in 'source\SN7C\MoldData_Mat1.pas' {MoldData_Mat},
  MoldData1 in 'source\SN7C\MoldData1.pas' {MoldData},
  FDExcelData_TYB1 in 'source\SN742\FDExcelData_TYB1.pas' {FDExcelData_TYB},
  HangTag1 in 'source\SNB2\HangTag1.pas' {HangTag},
  GlueCopy1 in 'source\SN22\GlueCopy1.pas' {GlueCopy},
  BOMVN_copy1 in 'source\SN22\BOMVN_copy1.pas' {BOMVN_copy},
  ToolingSetting in 'source\SN2A\ToolingSetting.pas' {ToolingSetting1},
  ScanTBBMTime in 'source\SNA51\ScanTBBMTime.pas' {ScanTBBMTime1},
  TPToFinished1 in 'source\SNB3\TPToFinished1.pas' {TPToFinished},
  PMR1 in 'source\SNB4\PMR1.pas' {PMR},
  ShoetestReceive in 'source\SN93\ShoetestReceive.pas' {ShoetestReceive1},
  ShoePlan in 'source\SNB5\ShoePlan.pas' {ShoePlan},
  TBSTime in 'source\SNA41\TBSTime.pas' {TBSTime1},
  TBClear in 'source\SNA8\TBClear.pas' {TBClear1},
  ChooseDPDR in 'source\SN27\ChooseDPDR.pas' {chooseDPDR1},
  PCData1 in 'source\SN82\PCData1.pas' {PCData},
  RFC_List1 in 'source\SNB6\RFC_List1.pas' {RFC_List},
  TrackingUpdateList1 in 'source\SN22\TrackingUpdateList1.pas' {TrackingUpdateList},
  Scan_InventoryList1 in 'source\SN631\Scan_InventoryList1.pas' {Scan_InventoryList},
  Memo_Material1 in 'source\SN22\Memo_Material1.pas' {Memo_Material},
  FDExcelData_Detai1 in 'source\SN741\FDExcelData_Detai1.pas' {FDExcelData_Detai},
  ColorSwatchScan1 in 'source\SNA22\ColorSwatchScan1.pas' {ColorSwatchScan},
  ManualEntry1 in 'source\SNA22\ManualEntry1.pas' {ManualEntry},
  PMR_Internal1 in 'source\SNC1\PMR_Internal1.pas' {PMR_Internal},
  SKUChoose1 in 'source\SNC1\SKUChoose1.pas' {SKUChoose},
  MoldData_ZSDH1 in 'source\SN7C\MoldData_ZSDH1.pas' {MoldData_ZSDH},
  SampeFinishShoeStock1 in 'source\SN45\SampeFinishShoeStock1.pas' {SampeFinishShoeStock},
  SampleFinishShoeStock_Detail1 in 'source\SN45\SampleFinishShoeStock_Detail1.pas' {SampleFinishShoeStock_Detail},
  TBDelayReason in 'source\SNB7\TBDelayReason.pas' {TBDelayReason1},
  ChooseDPDR3 in 'source\SNB7\ChooseDPDR3.pas' {ChooseDPDR2},
  Sample_TBRemake1 in 'source\SN2B\Sample_TBRemake1.pas' {Sample_TBRemake},
  Allshoe_List1 in 'source\SN632\Allshoe_List1.pas' {Allshoe_List},
  QRFormatTracking_Print1 in 'source\SN94\QRFormatTracking_Print1.pas' {QRFormatTracking_Print},
  QRFormatTracking1 in 'source\SN94\QRFormatTracking1.pas' {QRFormatTracking},
  QRSKU1 in 'source\SN94\QRSKU1.pas' {QRSKU},
  QRFormatScan1 in 'source\SN95\QRFormatScan1.pas' {QRFormatScan},
  DevelopTrainingCourses1 in 'source\SND1\DevelopTrainingCourses1.pas' {DevelopTrainingCourses},
  DevelopTrainingRecords1 in 'source\SND2\DevelopTrainingRecords1.pas' {DevelopTrainingRecords},
  DeveloperList1 in 'source\SND2\DeveloperList1.pas' {DeveloperList},
  CourseList1 in 'source\SND2\CourseList1.pas' {CourseList},
  DevelopTrainingReport1 in 'source\SND3\DevelopTrainingReport1.pas' {DevelopTrainingReport},
  LocalizationReport1 in 'source\SN6C\LocalizationReport1.pas' {LocalizationReport},
  scandata_Print1 in 'source\SN46\scandata_Print1.pas' {scandata_Print},
  scandata1 in 'source\SN46\scandata1.pas' {ScanData},
  Detail1 in 'source\SNA22\Detail1.pas' {Detail},
  UpdateDetail1 in 'source\SN741\UpdateDetail1.pas' {UpdateDetail},
  UsageCopy1 in 'source\SN22\UsageCopy1.pas' {UsageCopy},
  PartNo1 in 'source\SN22\PartNo1.pas' {PartNo},
  SampleNo1 in 'source\SN22\SampleNo1.pas' {SampleNo},
  SampleOrder_Developer1 in 'source\SN22\SampleOrder_Developer1.pas' {SampleOrder_Developer};

{$R *.res}


var   MutexHandle:Thandle;
begin
  Mutexhandle:=windows.CreateMutex(nil,true,'Develop.exe');
  if   Mutexhandle<>0   then
    begin
      if   getlasterror=windows.ERROR_ALREADY_EXISTS   then
        begin
          closehandle(Mutexhandle);
          halt;             
        end;
    end;
  Application.Initialize;
  login:=tlogin.create(application);
  login.Show;
  login.Update;
  //Application.CreateForm(TLOGIN, LOGIN);
  Application.Title := 'LIY ERP-Develop';
  Application.CreateForm(TDM2, DM2);
  Application.CreateForm(Tmain, main);
  Application.CreateForm(TDFC, DFC);
  login.hide;
  login.free;
  Application.Run;

end.
