unit Report_NXT_Print1;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, QRCtrls, QuickRpt, ExtCtrls, DB, DBTables, QRPDFFilt, StdCtrls, IniFiles;

type
  TNXT_Print_S = class(TForm)
    QuickRep1: TQuickRep;
    PageHeaderBand1: TQRBand;
    DetailBand1: TQRBand;
    QRDBText1: TQRDBText;
    Mas: TQuery;
    Det: TQuery;
    DataSource1: TDataSource;
    UpdateSQL1: TUpdateSQL;
    QRDBText2: TQRDBText;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    MasCGNO: TStringField;
    MasCLBH: TStringField;
    MasXqQty: TCurrencyField;
    MasQty: TCurrencyField;
    MasUSPrice: TCurrencyField;
    MasVNPrice: TCurrencyField;
    MasMemo: TStringField;
    MasBJNO: TStringField;
    MasCFMDate: TDateTimeField;
    MasUSERDate: TDateTimeField;
    MasUSERID: TStringField;
    MasYN: TStringField;
    MasYWPM: TStringField;
    MasDWBH: TStringField;
    QRSysData1: TQRSysData;
    PageFooterBand1: TQRBand;
    QRPDFFilter1: TQRPDFFilter;
    L1: TQRLabel;
    L2: TQRLabel;
    L21: TQRLabel;
    L22: TQRLabel;
    L24: TQRLabel;
    L16: TQRLabel;
    L14: TQRLabel;
    MasMEMO_1: TStringField;
    MasREMARK: TStringField;
    L25: TQRLabel;
    QRDBText10: TQRDBText;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRDBText6: TQRDBText;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRLabel7: TQRLabel;
    QRDBText16: TQRDBText;
    BWQY: TQuery;
    BWQYywsm: TStringField;
    MasPartAll: TStringField;
    QRDBText11: TQRDBText;
    MasZLNO: TMemoField;
    QRDBText7: TQRDBText;
    MasFDAll: TMemoField;
    L18: TQRLabel;
    QRLabel9: TQRLabel;
    L20: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel8: TQRLabel;
    QRDBText3: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    QRDBText12: TQRDBText;
    QRDBText13: TQRDBText;
    QRDBText14: TQRDBText;
    QRDBText15: TQRDBText;
    QRDBText17: TQRDBText;
    QRLabel16: TQRLabel;
    QRLabel17: TQRLabel;
    QRLabel10: TQRLabel;
    QRLabel11: TQRLabel;
    QRLabel12: TQRLabel;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    QRLabel15: TQRLabel;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRLabel20: TQRLabel;
    QRLabel21: TQRLabel;
    QRLabel22: TQRLabel;
    QRLabel23: TQRLabel;
    QRLabel24: TQRLabel;
    QRLabel25: TQRLabel;
    QRShape1: TQRShape;
    L17: TQRLabel;
    L15: TQRLabel;
    QRShape3: TQRShape;
    QRLabel26: TQRLabel;
    QRLabel27: TQRLabel;
    QRShape4: TQRShape;
    QRShape5: TQRShape;
    QRDBText19: TQRDBText;
    QRDBText20: TQRDBText;
    QRDBText21: TQRDBText;
    QRDBText22: TQRDBText;
    QRDBText23: TQRDBText;
    QRDBText24: TQRDBText;
    QRDBText25: TQRDBText;
    QRDBText26: TQRDBText;
    QRDBText27: TQRDBText;
    QRDBText28: TQRDBText;
    QRDBText29: TQRDBText;
    QRDBText30: TQRDBText;
    QRDBText31: TQRDBText;
    QRDBText32: TQRDBText;
    QRDBText33: TQRDBText;
    QRDBText34: TQRDBText;
    QRDBText35: TQRDBText;
    QRDBText36: TQRDBText;
    QRDBText37: TQRDBText;
    QRDBText38: TQRDBText;
    QRDBText39: TQRDBText;
    QRDBText40: TQRDBText;
    QRDBText41: TQRDBText;
    QRDBText42: TQRDBText;
    QRDBText43: TQRDBText;
    QRDBText44: TQRDBText;
    QRDBText45: TQRDBText;
    QRDBText46: TQRDBText;
    QRDBText47: TQRDBText;
    QRDBText48: TQRDBText;
    QRDBText50: TQRDBText;
    Query1: TQuery;
    StringField8: TStringField;
    StringField10: TStringField;
    StringField11: TStringField;
    CurrencyField3: TCurrencyField;
    CurrencyField4: TCurrencyField;
    CurrencyField5: TCurrencyField;
    CurrencyField8: TCurrencyField;
    CurrencyField9: TCurrencyField;
    CurrencyField10: TCurrencyField;
    CurrencyField11: TCurrencyField;
    CurrencyField12: TCurrencyField;
    CurrencyField13: TCurrencyField;
    CurrencyField14: TCurrencyField;
    CurrencyField15: TCurrencyField;
    CurrencyField16: TCurrencyField;
    CurrencyField17: TCurrencyField;
    CurrencyField18: TCurrencyField;
    CurrencyField19: TCurrencyField;
    CurrencyField20: TCurrencyField;
    CurrencyField21: TCurrencyField;
    CurrencyField22: TCurrencyField;
    CurrencyField23: TCurrencyField;
    CurrencyField24: TCurrencyField;
    CurrencyField25: TCurrencyField;
    CurrencyField26: TCurrencyField;
    CurrencyField27: TCurrencyField;
    CurrencyField28: TCurrencyField;
    CurrencyField29: TCurrencyField;
    CurrencyField30: TCurrencyField;
    CurrencyField31: TCurrencyField;
    CurrencyField32: TCurrencyField;
    CurrencyField33: TCurrencyField;
    CurrencyField34: TCurrencyField;
    CurrencyField35: TCurrencyField;
    CurrencyField36: TCurrencyField;
    QRShape6: TQRShape;
    QRShape7: TQRShape;
    QRShape8: TQRShape;
    QRShape9: TQRShape;
    QRShape10: TQRShape;
    QRShape11: TQRShape;
    QRShape12: TQRShape;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRShape15: TQRShape;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    QRShape20: TQRShape;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRDBText18: TQRDBText;
    QRLabel6: TQRLabel;
    QRDBText52: TQRDBText;
    QRDBText51: TQRDBText;
    QRLabel28: TQRLabel;
    QRLabel45: TQRLabel;
    QRLabel46: TQRLabel;
    QRExpr2: TQRExpr;
    QRExpr1: TQRExpr;
    QRExpr3: TQRExpr;
    QRExpr4: TQRExpr;
    QRExpr5: TQRExpr;
    QRExpr6: TQRExpr;
    QRExpr7: TQRExpr;
    QRExpr8: TQRExpr;
    QRShape23: TQRShape;
    QRShape24: TQRShape;
    QRShape25: TQRShape;
    QRShape26: TQRShape;
    QRShape27: TQRShape;
    QRShape28: TQRShape;
    QRLabel29: TQRLabel;
    QRShape29: TQRShape;
    QRShape30: TQRShape;
    QRLabel30: TQRLabel;
    QRLabel31: TQRLabel;
    QRLabel32: TQRLabel;
    QRLabel33: TQRLabel;
    QRLabel34: TQRLabel;
    QRShape31: TQRShape;
    QRShape32: TQRShape;
    QRShape33: TQRShape;
    QRLabel35: TQRLabel;
    QRLabel36: TQRLabel;
    QRLabel37: TQRLabel;
    QRLabel38: TQRLabel;
    QRLabel39: TQRLabel;
    QRShape34: TQRShape;
    QRShape35: TQRShape;
    QRShape36: TQRShape;
    QRShape37: TQRShape;
    QRShape38: TQRShape;
    QRShape39: TQRShape;
    QRShape40: TQRShape;
    QRShape41: TQRShape;
    QRShape42: TQRShape;
    QRShape43: TQRShape;
    QRLabel40: TQRLabel;
    QRLabel41: TQRLabel;
    QRShape44: TQRShape;
    QRShape45: TQRShape;
    QRShape46: TQRShape;
    QRShape47: TQRShape;
    QRLabel42: TQRLabel;
    QRLabel43: TQRLabel;
    QRLabel44: TQRLabel;
    QRLabel47: TQRLabel;
    QRLabel48: TQRLabel;
    QRLabel49: TQRLabel;
    QRDBText53: TQRDBText;
    QRShape48: TQRShape;
    QRShape49: TQRShape;
    QRShape50: TQRShape;
    QRShape51: TQRShape;
    QRShape52: TQRShape;
    QRShape53: TQRShape;
    QRShape54: TQRShape;
    QRShape56: TQRShape;
    khu: TQRLabel;
    QRShape2: TQRShape;
    QRShape55: TQRShape;
    QRShape57: TQRShape;
    QRShape58: TQRShape;
    QRLabel50: TQRLabel;
    QRLabel51: TQRLabel;
    QRLabel52: TQRLabel;
    QRLabel53: TQRLabel;
    Query1LastQty_TC1: TCurrencyField;
    Query1LastQty_NK1: TCurrencyField;
    Query1LastQty_HD1: TCurrencyField;
    Query1LastQty_KD1: TCurrencyField;
    Query1RKQty_TC1: TCurrencyField;
    Query1RKQty_NK1: TCurrencyField;
    Query1RKQty_HD1: TCurrencyField;
    Query1RKQty_KD1: TCurrencyField;
    Query1LastACC_TC1: TCurrencyField;
    Query1LastACC_NK1: TCurrencyField;
    Query1LastACC_HD1: TCurrencyField;
    Query1LastACC_KD1: TCurrencyField;
    Query1RKACC_TC1: TCurrencyField;
    Query1RKACC_NK1: TCurrencyField;
    Query1RKACC_HD1: TCurrencyField;
    Query1RKACC_KD1: TCurrencyField;
    Query1CKQty_TC1: TCurrencyField;
    Query1CKQty_NK1: TCurrencyField;
    Query1CKQty_HD1: TCurrencyField;
    Query1CKQty_KD1: TCurrencyField;
    Query1CKACC_TC1: TCurrencyField;
    Query1CKACC_NK1: TCurrencyField;
    Query1CKACC_HD1: TCurrencyField;
    Query1CKACC_KD1: TCurrencyField;
    Query1RemQty_TC1: TCurrencyField;
    Query1RemQty_NK1: TCurrencyField;
    Query1RemQty_HD1: TCurrencyField;
    Query1RemQty_KD1: TCurrencyField;
    Query1RemACC_TC1: TCurrencyField;
    Query1RemACC_NK1: TCurrencyField;
    Query1RemACC_HD1: TCurrencyField;
    Query1RemACC_KD1: TCurrencyField;
    QRDBText49: TQRDBText;
    QRDBText54: TQRDBText;
    QRDBText55: TQRDBText;
    QRDBText56: TQRDBText;
    QRDBText57: TQRDBText;
    QRDBText58: TQRDBText;
    QRDBText59: TQRDBText;
    QRDBText60: TQRDBText;
    QRDBText61: TQRDBText;
    QRDBText62: TQRDBText;
    QRDBText63: TQRDBText;
    QRDBText64: TQRDBText;
    QRDBText65: TQRDBText;
    QRDBText66: TQRDBText;
    QRDBText67: TQRDBText;
    QRDBText68: TQRDBText;
    QRDBText69: TQRDBText;
    QRDBText70: TQRDBText;
    QRDBText71: TQRDBText;
    QRDBText72: TQRDBText;
    QRDBText73: TQRDBText;
    QRDBText74: TQRDBText;
    QRDBText75: TQRDBText;
    QRDBText76: TQRDBText;
    QRDBText77: TQRDBText;
    QRDBText78: TQRDBText;
    QRDBText79: TQRDBText;
    QRDBText80: TQRDBText;
    QRDBText82: TQRDBText;
    QRDBText83: TQRDBText;
    QRDBText84: TQRDBText;
    QRDBText85: TQRDBText;
    QRShape59: TQRShape;
    QRLabel54: TQRLabel;
    Query1LastQty_NQ: TCurrencyField;
    Query1LastACC_NQ: TCurrencyField;
    Query1RKQty_NQ: TCurrencyField;
    Query1RKACC_NQ: TCurrencyField;
    Query1CKQty_NQ: TCurrencyField;
    Query1CKACC_NQ: TCurrencyField;
    Query1RemQty_NQ: TCurrencyField;
    Query1RemACC_NQ: TCurrencyField;
    QRDBText86: TQRDBText;
    QRDBText87: TQRDBText;
    QRDBText88: TQRDBText;
    QRDBText89: TQRDBText;
    QRDBText90: TQRDBText;
    QRDBText91: TQRDBText;
    QRDBText81: TQRDBText;
    QRDBText92: TQRDBText;
    QRDBText93: TQRDBText;
    Query1LastQty_NKNQ: TCurrencyField;
    Query1LastACC_NKNQ: TCurrencyField;
    Query1RemQty_NKNQ: TCurrencyField;
    Query1RemACC_NKNQ: TCurrencyField;
    Query1RKQty_NKNQ: TCurrencyField;
    Query1RKACC_NKNQ: TCurrencyField;
    Query1CKQty_NKNQ: TCurrencyField;
    Query1CKACC_NKNQ: TCurrencyField;
    QRLabel55: TQRLabel;
    QRShape60: TQRShape;
    QRDBText94: TQRDBText;
    QRDBText95: TQRDBText;
    QRDBText96: TQRDBText;
    QRDBText97: TQRDBText;
    QRDBText98: TQRDBText;
    QRDBText99: TQRDBText;
    QRDBText100: TQRDBText;
    QRDBText101: TQRDBText;
    procedure FormCreate(Sender: TObject);
    procedure FormDestroy(Sender: TObject);
  private
    Account_N62_CheckFactory:String;
    { Private declarations }
    procedure ReadIni();
  public
    { Public declarations }
    WH_DiplayFormat:String;
  end;

var
  NXT_Print_S: TNXT_Print_S;

implementation

uses Report_NXT1, main1, FunUnit;

{$R *.dfm}

procedure TNXT_Print_S.ReadIni();
var MyIni :Tinifile;
    AppDir, ComFullName, Address, TelNumber, FaxNumber:string;
    ComName, ComNameCH : string;
begin
  //
  AppDir:=ExtractFilePath(Application.ExeName);
  ComFullName:='Vinh Long Footwear Co.LTD';
  Address:='Hoa Phu Industrial Zone, Vinh Long Province, Vietnam';
  TelNumber:='TEL:+84-703-962052';
  FaxNumber:='FAX:+84-703-96251';
  Account_N62_CheckFactory:='N';
  WH_DiplayFormat:='#,##0.00';
  if FileExists(AppDir+'\ComName.ini')=true then
  begin
    try
      MyIni := Tinifile.Create(AppDir+'\ComName.ini');
      ComFullName:=MyIni.ReadString('ERP','ComFullName','');
      //
      Address:=MyIni.ReadString('ERP','Address','Hoa Phu Industrial Zone, Vinh Long Province, Vietnam');
      TelNumber:=MyIni.ReadString('ERP','TelNumber','TEL:+84-703-962052');
      FaxNumber:=MyIni.ReadString('ERP','FaxNumber','FAX:+84-703-96251');

      ComName:=MyIni.ReadString('ERP','ComName','');
      ComNameCH:=MyIni.ReadString('ERP','ComNameCH','');
      Account_N62_CheckFactory:=MyIni.ReadString('ERP','Account_N62_CheckFactory','N');
      WH_DiplayFormat:=MyIni.ReadString('Warehouse','DiplayFormat','#,##0.00');
      //
    finally
      MyIni.Free;
    end;
  end;
  //
  L1.Caption:=ComName;
  L2.Caption:=ComNameCH;
  QRExpr2.Mask:=WH_DiplayFormat;
  QRExpr3.Mask:=WH_DiplayFormat;
  QRExpr5.Mask:=WH_DiplayFormat;
  QRExpr7.Mask:=WH_DiplayFormat;
  QRDBText19.Mask:=WH_DiplayFormat;
  QRDBText20.Mask:=WH_DiplayFormat;
  QRDBText21.Mask:=WH_DiplayFormat;
  QRDBText22.Mask:=WH_DiplayFormat;
  QRDBText27.Mask:=WH_DiplayFormat;
  QRDBText29.Mask:=WH_DiplayFormat;
  QRDBText31.Mask:=WH_DiplayFormat;
  QRDBText33.Mask:=WH_DiplayFormat;
  QRDBText35.Mask:=WH_DiplayFormat;
  QRDBText37.Mask:=WH_DiplayFormat;
  QRDBText39.Mask:=WH_DiplayFormat;
  QRDBText41.Mask:=WH_DiplayFormat;
  QRDBText43.Mask:=WH_DiplayFormat;
  QRDBText45.Mask:=WH_DiplayFormat;
  QRDBText47.Mask:=WH_DiplayFormat;
  QRDBText50.Mask:=WH_DiplayFormat;

  QRDBText49.Mask:=WH_DiplayFormat;
  QRDBText54.Mask:=WH_DiplayFormat;
  QRDBText55.Mask:=WH_DiplayFormat;
  QRDBText56.Mask:=WH_DiplayFormat;
  QRDBText61.Mask:=WH_DiplayFormat;
  QRDBText62.Mask:=WH_DiplayFormat;
  QRDBText63.Mask:=WH_DiplayFormat;
  QRDBText64.Mask:=WH_DiplayFormat;
  QRDBText69.Mask:=WH_DiplayFormat;
  QRDBText70.Mask:=WH_DiplayFormat;
  QRDBText71.Mask:=WH_DiplayFormat;
  QRDBText72.Mask:=WH_DiplayFormat;
  QRDBText79.Mask:=WH_DiplayFormat;
  QRDBText80.Mask:=WH_DiplayFormat;
  QRDBText81.Mask:=WH_DiplayFormat;
  QRDBText82.Mask:=WH_DiplayFormat;

  with Det do
  begin
    active:=false;
    sql.Clear;
    sql.Add('select Factory from bgszl where gsdh='''+Report_NXT.cbx4.Text+'''');
    active:=true;
  end;
  if ((Account_N62_CheckFactory<>'') and (Account_N62_CheckFactory='Y')) then
  begin
    khu.Caption:='KHU: '+Det.FieldByName('Factory').AsString;
  end else
  begin
    khu.Caption:='';
  end;
end;

procedure TNXT_Print_S.FormCreate(Sender: TObject);
var i,j:integer;
    PartALl,FD_ALL:string;
    //20151012 Converse 特定顏色指定
    isWhite,isBVWhite,isBlack,isNatural,isCharcoal:boolean;
    Converse_Memo:String;
begin
  ReadIni();
end;

procedure TNXT_Print_S.FormDestroy(Sender: TObject);
begin
  NXT_Print_S:=nil;
end;

end.
